config/routes.rb
Rails.application.routes.draw do

  root 'publics#home'
  get 'about', to: 'publics#about'
  get 'published_articles', to: 'publics#publics_articles'
  get 'published_articles/:id', to: 'publics#show_article', as: 'un_article'
  get 'published_emissions', to: 'publics#publics_emissions'
  get 'published_emissions/:id', to: 'publics#show_emission', as: 'une_emission'
  devise_for :users
  resources :articles
  resources :media
  resources :emissions
  resources :contact_form, only: %i[new create]
  # get 'published.articles', to: 'publics#publics_articles'
  # get '/published.articles/:id', to: 'publics#show_article', as: 'article'
end

app/controllers/publics_controller.rb
class PublicsController < ApplicationController
  def home; end

  def about; end

  def show_article
    @l_article = Article.find(params[:id])
  end

  def publics_articles
    @les_articles = Article.all
  end

  def show_emission
    @l_emission = Emission.find(params[:id])
  end

  def publics_emissions
    @les_emissions = Emission.all
  end
end

app/helpers/publics_helper.rb
module PublicsHelper
end

app/views/publics/_article.html.erb
<section class="container py-5" id="<%= dom_id article %>">
  <div class="row">
    <div class="col-8 mx-auto">
      <article class="posted-article">
        <h1>
          <%= article.title %>
        </h1>
        <h2>
          <%= article.subltitle %>
        </h2>
        <% if article.contents.attached?  %>
          <%if article.contents[0].image?%>
            <figure>
              <%= image_tag(article.contents[0], class: "image", alt: "Card image cap") %>
              <figcaption><%= article.description %></figcaption>
            </figure>
          <%end%>
        <%end%>
        <p>
          <%= article.contenu %>
        </p>
        <p>
          <%= article.user.name %>
        </p>
      </article>
    </div>
  </div>
  <% if article.contents.attached? %>
    <div class="album py-5 bg-body-tertiary">
      <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
          <% article.contents.each do |content| %>
            <%if content.image?%>
              <div class="col">
                <div class="card shadow-sm">
                  <div class="card-body">
                    <%= image_tag(content, class: "card-img-top", alt: "Card image cap") %>
                  </div>
                </div>
              </div>
            <%elsif content.video?%>
              <div class="col">
                <div class="card shadow-sm">
                  <div class="card-body">
                    <video
            controls
            muted
            src="<%= rails_blob_url(content) %>"
            width="100%" type="<%= content.content_type%>">
                      Sorry, your browser doesn't support embedded videos, but don't worry, you can
                      <a href="https://archive.org/details/BigBuckBunny_124">download it</a>
                      and watch it with your favorite video player!
                    </video>
                  </div>
                </div>
              </div>
            <%elsif content.audio?%>
              <div class="col">
                <div class="card shadow-sm">
                  <div class="card-body">
                    <%= audio_tag(url_for(content), controls: true)%>
                  </div>
                </div>
              </div>
            <%else%>
              <div class="col">
                <div class="card shadow-sm">
                  <div class="card-body">
                    <%= link_to content.filename, content %>
                    <%= link_to "Download link", content %>
                  </div>
                </div>
              </div>
            <%end%>
          <% end %>
        </div>
      </div>
    </div>
  <%end%>
</section>

app/views/publics/_emission.html.erb
<section class="container fluid emission" id="<%= dom_id emission %>" >
  <div class="container col-xxl-8 px-4 py-5">
    <div class="row flex-lg-row-reverse align-items-center g-5 py-5">
      <div class="col-10 col-sm-8 col-lg-6">
        <%= image_tag(emission.poster, class: "d-block mx-lg-auto img-fluid",  size: "700x500", loading: "lazy" , alt: "Emission logo") %>
      </div>
      <div class="col-lg-6">
        <h1 class="display-5 fw-bold text-body-emphasis lh-1 mb-3">    <%= emission.title %></h1>
        <p class="lead">
          <%= emission.description %>
          <p>
            Pr&eacute;senter par&nbsp;:&nbsp;<strong>
              <%= emission.user_id %>  </strong>
          </p>
        </div>
      </div>
    </div>
    <%if emission.media %>
      <div class="album py-5 bg-body-tertiary">
        <div class="container">
          <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            <% emission.media.each do |item|%>
              <div class="col">
                <div class="card shadow-sm">
                  <%= image_tag(emission.poster, class: "card-img-top",  style: "width: 100%; height:225", loading: "lazy" , alt: "Emission logo") %>
                  <div class="card-body">
                    <p class="card-title"> <%= item.title %></p>
                    <p class="card-text">
                      <%= item.description %>
                    </p>
                    <div class="d-flex justify-content-between align-items-center">
                      <%= audio_tag(url_for(item.content), controls: true)%>
                    </div>
                  </div>
                  <div class="card-footer">
                    <small class="text-body-secondary"><%= item.created_at %></small>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    <%end%>
  </section>

app/views/publics/about.html.erb
<section class="container-fluid about-sections" id="about-statement" >
  <div class="px-3 py-5 my-2 text-center ">
    <h1 class="display-5 fw-bold text-body-emphasis mt-5">Radio T&eacute;l&eacute; Patriarche</h1>
    <%= image_tag( "logo.jpg", class: "d-block mx-auto mb-4", alt: "logo", size: "200x100") %>
    <div class="col-lg-8 mx-auto thediv bended-shadow">
      <p class="lead mb-4">Quickly design and customize responsive mobile-first sites with Bootstrap, the world’s most popular front-end open source toolkit, featuring Sass variables and mixins, responsive grid system, extensive prebuilt components, and powerful JavaScript plugins.</p>
      <p class="lead mb-2">
        Cillum fugiat voluptate voluptate laboris est. Velit aliquip voluptate adipisicing cillum duis minim amet sit aliqua officia consectetur. Dolore labore officia cillum commodo esse aliqua. Non fugiat enim anim reprehenderit sit sit. Quis enim nostrud amet cupidatat fugiat ut in excepteur amet adipisicing. Voluptate dolor enim ullamco consequat nulla consequat enim. Ea irure cupidatat cupidatat mollit eiusmod laboris.
      </p>
      <p class="lead mb-2">
        Cillum fugiat voluptate voluptate laboris est. Velit aliquip voluptate adipisicing cillum duis minim amet sit aliqua officia consectetur. Dolore labore officia cillum commodo esse aliqua. Non fugiat enim anim reprehenderit sit sit. Quis enim nostrud amet cupidatat fugiat ut in excepteur amet adipisicing. Voluptate dolor enim ullamco consequat nulla consequat enim. Ea irure cupidatat cupidatat mollit eiusmod laboris.
      </p>
    </div>
  </div>
</section>
<section class="container-fluid my-5 d-flex flex-column justify-content-center" id="about-mission" 
style="background-color: rgba(1,1,1,0.2); background-image: url(<%= image_path "logo.jpg"%>);height: 100vh; background-attachment: fixed; background-position: center; background-repeat: no-repeat; background-size: cover; cover; background-blend-mode: multiply;"
>
  <div class="p-5 text-center rounded-3 thediv">
    <h1 class="text-body-emphasis">Radio T&eacute;l&eacute; Patriarche</h1>
    <div class="row">
      <article class="col">
        <h2>Nos valeurs</h2>
        <p>Proin gravida nibh vel velit auctor aliquet. Aenean sollicitudin, lorem quis bibendum auctor, nisi elit consequat ipsum, nec sagittis sem nibh id elit. Duis sed odio sit amet nibh vulputate cursus a sit amet mauris. Morbi accumsan ipsum velit. Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non  mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit. Sed ut imperdiet nisi. Proin condimentum fermentum nunc. Etiam pharetra, erat sed fermentum feugiat, velit mauris egestas quam, ut aliquam massa nisl quis neque. Suspendisse in orci enim.</p>
      </article>
      <article class="col">
        <h2>Notre mission</h2>
        <p>Proin gravida nibh vel velit auctor aliquet. Aenean sollicitudin, lorem quis bibendum auctor, nisi elit consequat ipsum, nec sagittis sem nibh id elit. Duis sed odio sit amet nibh vulputate cursus a sit amet mauris. Morbi accumsan ipsum velit. Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non  mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit. Sed ut imperdiet nisi. Proin condimentum fermentum nunc. Etiam pharetra, erat sed fermentum feugiat, velit mauris egestas quam, ut aliquam massa nisl quis neque. Suspendisse in orci enim.</p>
      </article>
    </div>
  </div>
</section>
<section id="about-team">
  <div class="container">
    <div class="intro">
      <h2 class="text-center">Team </h2>
      <p class="text-center">Nunc luctus in metus eget fringilla. Aliquam sed justo ligula. Vestibulum nibh erat, pellentesque ut laoreet vitae.</p>
    </div>
    <div class="row people">
      <div class="col-md-6 col-lg-4 item">
        <div class="box">
          <%= image_tag("team_f.jpg", class: "rounded-circle", alt: "team member name")%>
          <h3 class="name">Ben Johnson</h3>
          <p class="title">Musician</p>
          <p class="description">Aenean tortor est, vulputate quis leo in, vehicula rhoncus lacus. Praesent aliquam in tellus eu gravida. Aliquam varius finibus est, et interdum justo suscipit id. Etiam dictum feugiat tellus, a semper massa. </p>
          <div class="social"><a href="#"><i class="bi bi-facebook"></i></a><a href="#"><i class="bi bi-twitter"></i></a><a href="#"><i class="bi bi-instagram"></i></a></div>
        </div>
      </div>
      <div class="col-md-6 col-lg-4 item">
        <div class="box">
          <%= image_tag("team-member.jpg", class: "rounded-circle", alt: "team member name") %>
          <h3 class="name">Emily Clark</h3>
          <p class="title">Artist</p>
          <p class="description">Aenean tortor est, vulputate quis leo in, vehicula rhoncus lacus. Praesent aliquam in tellus eu gravida. Aliquam varius finibus est, et interdum justo suscipit id. Etiam dictum feugiat tellus, a semper massa. </p>
          <div class="social"><a href="#"><i class="bi bi-facebook"></i></a><a href="#"><i class="bi bi-twitter"></i></a><a href="#"><i class="bi bi-instagram"></i></a></div>
        </div>
      </div>
      <div class="col-md-6 col-lg-4 item">
        <div class="box">
          <%= image_tag("team_f.jpg", class: "rounded-circle", alt: "team member name")%>
          <h3 class="name">Carl Kent</h3>
          <p class="title">Stylist</p>
          <p class="description">Aenean tortor est, vulputate quis leo in, vehicula rhoncus lacus. Praesent aliquam in tellus eu gravida. Aliquam varius finibus est, et interdum justo suscipit id. Etiam dictum feugiat tellus, a semper massa. </p>
          <div class="social"><a href="#"><i class="bi bi-facebook"></i></a><a href="#"><i class="bi bi-twitter"></i></a><a href="#"><i class="bi bi-instagram"></i></a></div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/publics/home.html.erb
<section c
lass="container-fluid col-xxl-8 px-4 py-5 mt-5 align-items-center home-sections" 
style="background-color: orange; background-image: url(<%= image_path "splash.png"%>);height: 100vh; background-attachment: fixed; background-position: center; background-repeat: no-repeat; background-size: cover; cover; background-blend-mode: multiply;"
id="home-hero">
  <div class="row py-5 w-100 h-100">
    <div class="col-lg-6 me-auto h-100 d-flex flex-column justify-content-center p-5">
      <h1 class="display-5 fw-bold text-body-emphasis lh-1 mb-3">Radio T&eacute;l&eacute; Patriarche</h1>
      <p class="lead">Que l&apos;&eacute;motion soit!</p>
      <div class="d-grid gap-4 d-md-flex justify-content-md-start">
        <button type="button" class="button-55">
          Nos emissions
        </button>
        <button class="button-55">
          Partagez avec nous
        </button>
      </div>
    </div>
  </div>
</div>
</section>
<div class="divider-b"></div>
<section class="text-secondary px-2 py-5 text-center home-sections" id="home-direct">
  <div class="py-2 w-100">
    <h1 class="display-5 fw-bold">T&eacute;l&eacute; Patriarche en directe!</h1>
    <div class="col-lg-8 mx-auto">
      <!-- 16:9 aspect ratio -->
      <div class="embed-responsive embed-responsive-16by9">
        <iframe class="embed-responsive-item" 
            src="https://www.youtube.com/embed/NiRIbKwAejk?si=aVXDKGhjpyTntmSI" 
            allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" 
            referrerpolicy="strict-origin-when-cross-origin" 
            title="Live news"
            allowfullscreen
          >
        </iframe>
      </div>
    </div>
  </div>
</section>
<div class="divider-b"></div>
<section class="text-secondary px-4 py-5 text-center home-sections" 
style="background-color: rgba(1,1,1,0.2); background-image: url(<%= image_path "logo.jpg"%>);height: 100vh; background-attachment: fixed; background-position: center; background-repeat: no-repeat; background-size: cover; cover; background-blend-mode: multiply;"
id="home-about">
  <div class="py-5 thediv bended-shadow content">
    <h1 class="display-5 fw-bold text-black">Radio T&eacute;l&eacute; Patriarche</h1>
    <div class="col-lg-6 mx-auto">
      <p class="fs-5 mb-4">
        Pellentesque habitant morbi tristique senectus et netus et malesuada
      </p>
      <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
        <button type="button" class="button-55">En savoir plus ...</button>
        <button type="button" class="button-55">Notre &eacute;quipe</button>
      </div>
    </div>
  </div>
</section>
<div class="divider-b"></div>
<section class="container-fluid px-2 home-sections">
  <div id="myCarousel" class="carousel slide mb-6" data-bs-ride="carousel" id="home-carousel">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <!--<svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="var(--bs-secondary-color)"/></svg>-->
        <%= image_tag("emission.jpg", alt: "emission", class: "bd-placeholder-img w-100 h-100" ) %>
        <div class="container">
          <div class="carousel-caption text-start">
            <h1>Emission headline</h1>
            <p class="opacity-75">Some representative placeholder content for the first slide of the carousel.</p>
            <p><a class="btn btn-lg btn-primary" href="#">En saavoir plus ...</a></p>
          </div>
        </div>
      </div>
      <div class="carousel-item">
        <!--<svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="var(--bs-secondary-color)"/></svg>-->
        <%= image_tag("emission2.jpg", alt: "emission", class: "bd-placeholder-img w-100 h-100" ) %>
        <div class="container">
          <div class="carousel-caption">
            <h1>Emission headline.</h1>
            <p>Some representative placeholder content for the second slide of the carousel.</p>
            <p><a class="btn btn-lg btn-primary" href="#">En savoir plus ...</a></p>
          </div>
        </div>
      </div>
      <div class="carousel-item">
        <!--<svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="var(--bs-secondary-color)"/></svg>-->
        <%= image_tag("emission.jpg", alt: "emission", class: "bd-placeholder-img w-100 h-100" ) %>
        <div class="container">
          <div class="carousel-caption text-end">
            <h1>Emission headline.</h1>
            <p>Some representative placeholder content for the third slide of this carousel.</p>
            <p><a class="btn btn-lg btn-primary" href="#">En savoir plus ...</a></p>
          </div>
        </div>
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
</section>

app/views/publics/publics_articles.html.erb
<section class="container-fluid py-5" id="articles-page">
  <p style="color: green"><%= notice %></p>
  <div class="container py-5">
    <% if @les_articles && !@les_articles.empty? %>
      <h1>Articles</h1>
      <% @les_articles.each do |article| %>
        <div id="articles">
          <div class="card mb-3">
            <div class="row no-gutters">
              <div class="col-md-4">
                <% if article.contents.attached?  %>
                  <%if article.contents[0].image?%>
                    <%= image_tag(article.contents[0], class: "card-image", alt: "article image") %>
                  <%end%>
                <%end%>
              </div>
              <div class="col-md-8">
                <div class="card-body">
                  <h5 class="card-title"><%= article.title %></h5>
                  <p class="card-text"><%= article.description %></p>
                  <p>
                    <%= link_to 'Voir plus ...', un_article_path(article) %>
                  </p>
                </div>
                <div class="card-footer">
                  <p class="card-text">Post&eacute;&nbsp;le&nbsp;<small class="text-muted"><%= article.created_at %></small></p>
                  <p class="card-text">Modifi&eacute;&nbsp;le&nbsp;<small class="text-muted"><%= article.updated_at %></small></p>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <%else%>
      <div class="bg-transparent text-secondary px-4 py-5 text-center">
        <div class="py-5">
          <h1 class="display-5 fw-bold text-white">Articles</h1>
          <div class="col-lg-6 mx-auto d-flex flex-column justify-content-center align-items-center gap-4">
            <p class="fs-5 mb-4 text-white">Articles indisponibles pour le temporairement. Veuillez profiter de nos &eacute;missions. Bonne &eacute;coute.</p>
            <%= render "shared/loader01"%>
          </div>
        </div>
      </div>
    <%end%>
  </div>
</section>

app/views/publics/publics_emissions.html.erb
<p style="color: green"><%= notice %></p>
<section class="container-fluid p-5 mt-5" id="emissions-page">
  <% if @les_emissions && !@les_emissions.empty? %>
    <h1>Emissions</h1>
    <% @les_emissions.each do |emission| %>
      <div class="card mb-3 bended-shadow" style="max-width: 540px;">
        <div class="row no-gutters">
          <div class="col-md-4">
            <%= image_tag(emission.poster, class: "card-image", alt: "#{emission.title} logo") %>
          </div>
          <div class="col-md-8">
            <div class="card-body">
              <h5 class="card-title"><%= emission.title %></h5>
              <p class="card-text"><%= emission.description %></p>
              <p>
                <%= link_to 'Voir plus ...', une_emission_path(emission) %>
              </p>
            </div>
            <div class="card-footer">
              <p class="card-text"><small class="text-muted"><%= emission.created_at %></small></p>
              <p class="card-text"><small class="text-muted"><%= emission.updated_at %></small></p>
            </div>
          </div>
        </div>
      </div>
    <%else%>
      <div class="bg-transparent text-secondary px-4 py-5 text-center">
        <div class="py-5">
          <h1 class="display-5 fw-bold text-white">Emissions</h1>
          <div class="col-lg-6 mx-auto d-flex flex-column justify-content-center align-items-center gap-4">
            <p class="fs-5 mb-4 text-white">Emissions indisponibles pour le temporairement. Veuillez profiter du Live. Bonne &eacute;coute.</p>
            <%= render "shared/loader01"%>
          </div>
        </div>
      </div>
    <% end %>
  </section>

app/views/publics/show_article.html.erb
<p style="color: green"><%= notice %></p>
<%#= render @l_article %>
<%= render partial: "article", object: @l_article %>

app/views/publics/show_emission.html.erb
<%#= render @l_emission %>
<%= render partial: "emission", object: @l_emission %>