config/routes.rb
Rails.application.routes.draw do

  root 'publics#home'
  get 'about', to: 'publics#about'
  get 'published_articles', to: 'publics#publics_articles'
  get 'published_articles/:id', to: 'publics#show_article', as: 'un_article'
  get 'published_emissions', to: 'publics#publics_emissions'
  get 'published_emissions/:id', to: 'publics#show_emission', as: 'une_emission'
  devise_for :users
  resources :articles
  resources :media
  resources :emissions
  resources :contact_form, only: %i[new create]
  # get 'published.articles', to: 'publics#publics_articles'
  # get '/published.articles/:id', to: 'publics#show_article', as: 'article'
end

app/views/shared/_contact_flash.html.erb
<% if flash %>
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>">
      <%= value %>
    </div>
  <% end %>
<%end%>

app/views/shared/_flash.html.erb
       <% if notice %>
       <p class="notice"><%= notice %></p>
       <%end%>
       <%if alert%>
       <p class="alert"><%= alert %></p>
       <%end%>

app/views/shared/_footer.html.erb
<div class="b-example-divider"></div>
<div class="container-fluid">
  <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
    <div class="col-md-4 d-flex align-items-center">
      <%= link_to(root_path, class: "mb-3 me-2 mb-md-0 text-body-secondary text-decoration-none lh-1") do %>
        <%= image_tag("logo.jpg", alt: "logo", size: "150x75")%>
      <%end%>
      <span class="mb-3 mb-md-0 text-body-secondary">&copy; 2024 RTP, Inc</span>
    </div>
    <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
      <li class="ms-3"><a class="text-body-secondary" href="#"><i class="bi bi-facebook"></i></a></li>
      <li class="ms-3"><a class="text-body-secondary" href="#"><i class="bi bi-instagram"></i></a></li>
      <li class="ms-3"><a class="text-body-secondary" href="#"><i class="bi bi-twitter"></i></a></li>
    </ul>
  </footer>
</div>

app/views/shared/_loader01.html.erb
<div class="loader01"></div>

app/views/shared/_public_header.html.erb
<header class="container-fluid fixed-top header-glass" id="public-header">
  <div class="site-navbar-top d-none d-md-block px-4">
    <div class="container-fluid py-1 border-bottom">
      <div class="row align-items-center">
        <div class="col-6">
          <div class="d-flex align-items-center justify-content-start gap-3">
            <a href="#" class="d-flex align-items-center">
              <span class="bi bi-envelope mr-2"></span>
              <span class="d-none d-md-inline-block">info@patriache.com</span>
            </a>
            <a href="#" class="d-flex align-items-center">
              <span class="bi bi-telephone-forward mr-2"></span>
              <span class="d-none d-md-inline-block">+509 88 88 88 88</span>
            </a>
          </div>
        </div>
        <div class="col-6">
          <div class="d-flex align-items-center justify-content-end">
            <a href="#" class="p-2 pl-0"><span class="bi bi-twitter"></span>
              <!--<i class="bi bi-twitter"></i>-->
            </a>
            <a href="#" class="p-2 pl-0"><span class="bi bi-facebook"></span>
              <!--<i class="bi bi-facebook"></i>-->
            </a>
            <a href="#" class="p-2 pl-0"><span class="bi bi-linkedin"></span>
              <!--  <i class="bi bi-linkedin"></i>-->
            </a>
            <a href="#" class="p-2 pl-0"><span class="bi bi-instagram"></span>
              <!--<i class="bi bi-instagram"></i>-->
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
  <nav class="navbar navbar-expand-md navbar-light px-4">
    <!--<nav class="navbar navbar-expand-md navbar-light fixed-top bg-transparent">-->
    <div class="container-fluid">
      <%= link_to root_path , class:"navbar-brand" do %>
        <%= image_tag 'logo.jpg', alt: "logo" %>
      <% end %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav ms-auto mb-2 mb-md-0">
          <li class="nav-item">
            <%= link_to root_path, class: "nav-link active", aria: { current: "page" }  do %>
              Radio T&eacute;l&eacute; Patriarche
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to about_path, class: "nav-link" do %>
              A propos de nous
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to published_articles_path , class: "nav-link" do %>
              Articles
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to published_emissions_path, class: "nav-link" do %>
              Emissions
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to new_contact_form_path, class: "nav-link" do %>
              Contactez-nous
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/shared/_public_social.html.erb
<div class="icon-bar">
  <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
  <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
  <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
  <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></a>
  <a href="#" class="youtube"><i class="bi bi-youtube"></i></a>
  <a href="#" class="phone"><i class="bi bi-telephone"></i></a>
  <a href="#" class="email"><i class="bi bi-envelope-arrow-down"></i></a>
</div>