config/routes.rb
Rails.application.routes.draw do

  root 'publics#home'
  get 'about', to: 'publics#about'
  get 'published_articles', to: 'publics#publics_articles'
  get 'published_articles/:id', to: 'publics#show_article', as: 'un_article'
  get 'published_emissions', to: 'publics#publics_emissions'
  get 'published_emissions/:id', to: 'publics#show_emission', as: 'une_emission'
  devise_for :users
  resources :articles
  resources :media
  resources :emissions
  resources :contact_form, only: %i[new create]
  # get 'published.articles', to: 'publics#publics_articles'
  # get '/published.articles/:id', to: 'publics#show_article', as: 'article'
end

app/models/emission.rb
class Emission < ApplicationRecord
  belongs_to :user
  has_one_attached :poster
  has_many :media
end

app/controllers/emissions_controller.rb
class EmissionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_emission, only: %i[show edit update destroy]

  # GET /emissions or /emissions.json
  def index
    @emissions = Emission.all
  end

  # GET /emissions/1 or /emissions/1.json
  def show; end

  # GET /emissions/new
  def new
    @emission = Emission.new
  end

  # GET /emissions/1/edit
  def edit; end

  # POST /emissions or /emissions.json
  def create
    @emission = Emission.new(emission_params)
    @emission.user = current_user

    respond_to do |format|
      if @emission.save
        format.html { redirect_to emission_url(@emission), notice: 'Emission was successfully created.' }
        format.json { render :show, status: :created, location: @emission }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @emission.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /emissions/1 or /emissions/1.json
  def update
    respond_to do |format|
      if @emission.update(emission_params)
        format.html { redirect_to emission_url(@emission), notice: 'Emission was successfully updated.' }
        format.json { render :show, status: :ok, location: @emission }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @emission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /emissions/1 or /emissions/1.json
  def destroy
    @emission.destroy

    respond_to do |format|
      format.html { redirect_to emissions_url, notice: 'Emission was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_emission
    @emission = Emission.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def emission_params
    params.require(:emission).permit(:title, :description, :poster, :user_id)
  end
end

app/helpers/emissions_helper.rb
module EmissionsHelper
end

app/views/emissions/_emission.html.erb
<div id="<%= dom_id emission %>">
  <p>
    <strong>Title:</strong>
    <%= emission.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= emission.description %>
  </p>

  <p>
    <strong>Poster:</strong>
    <%= link_to emission.poster.filename, emission.poster if emission.poster.attached? %>
  </p>


<%if emission.media %>
<h3>yo la</h3>
  <ul>

  <% emission.media.each do |item|%>
   <li> <%= item.title %></li>
  <% end %>

  </ul>
  <%end%>

  <p>
    <strong>User:</strong>
    <%= emission.user_id %>
  </p>

</div>

app/views/emissions/_form.html.erb
<%= form_with(model: emission) do |form| %>
  <% if emission.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(emission.errors.count, "error") %> prohibited this emission from being saved:</h2>

      <ul>
        <% emission.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :poster, style: "display: block" %>
    <%= form.file_field :poster %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/emissions/edit.html.erb
<h1>Editing emission</h1>

<%= render "form", emission: @emission %>

<br>

<div>
  <%= link_to "Show this emission", @emission %> |
  <%= link_to "Back to emissions", emissions_path %>
</div>

app/views/emissions/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Emissions</h1>

<div id="emissions">
  <% @emissions.each do |emission| %>
    <%
=begin%>
 <%= render emission %> 
<%
=end%>
<h2><%= emission.title %></h2>

  <p>
    <strong>Description:</strong>
    <%= emission.description %>
  </p>

  <p>
    <strong>Poster:</strong>
    <%= link_to emission.poster.filename, emission.poster if emission.poster.attached? %>
  </p>










    <p>
      <%= link_to "Show this emission", emission %>
    </p>
  <% end %>
</div>


<%= link_to "New emission", new_emission_path %>

app/views/emissions/new.html.erb
<h1>New emission</h1>

<%= render "form", emission: @emission %>

<br>

<div>
  <%= link_to "Back to emissions", emissions_path %>
</div>

app/views/emissions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @emission %>


<div>
  <%= link_to "Edit this emission", edit_emission_path(@emission) %> |
  <%= link_to "Back to emissions", emissions_path %>

  <%= button_to "Destroy this emission", @emission, method: :delete %>
</div>